blank_issues_enabled: false
contact_links:
  - name: Bug Report
    url: https://github.com/ROFIES-IIITP/Raspberry-Pi/issues/new?template=bug_report.md
    about: Report a bug to help us improve
  - name: Feature Request
    url: https://github.com/ROFIES-IIITP/Raspberry-Pi/issues/new?template=feature_request.md
    about: Suggest a new feature or enhancement
  - name: Project Idea
    url: https://github.com/ROFIES-IIITP/Raspberry-Pi/issues/new?template=project_idea.md
    about: Propose a new project idea
  - name: Question
    url: https://github.com/ROFIES-IIITP/Raspberry-Pi/issues/new?template=question.md
    about: Ask a question about this project
